development:
  sessions:
    default:
      database: drift_book_dev
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0

test:
  sessions:
    default:
      database: drift_book_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: drift_book_prod
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0